FROM mcr.microsoft.com/dotnet/sdk:7.0 AS dev
WORKDIR /app/src
COPY . .
RUN dotnet restore "./asg.identity.csproj"
RUN dotnet build "./asg.identity.csproj"
RUN chmod 755 ./entrypoint.sh
ENTRYPOINT [ "sh", "./entrypoint.sh" ]