GET https://localhost:3103/connect/userinfo
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0RDdBNTI0OTM3NEU0OTRBRUM0OTdBNzk4M0FDOTdCIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMTAzIiwibmJmIjoxNzAyNjY1MzE0LCJpYXQiOjE3MDI2NjUzMTQsImV4cCI6MTcwMjY2ODkxNCwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInVzZXIiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJiYWNrZW5kLWZvci1mcm9udGVuZCIsInN1YiI6IjY0MjgyZjk0LWIyYWItNDJiNi05NTIxLTYxMWRiMjI1YmI5OSIsImF1dGhfdGltZSI6MTcwMjY2NTMxMywiaWRwIjoibG9jYWwiLCJzaWQiOiJDRjgxNzJEQjVBN0U1QkY5NjFBOTJDNENEM0M5M0VDOSIsImp0aSI6IjZEN0VENjRCQTM0NzUwNjNDMTNCNEMyNTE1MkIyQkQ0In0.S8689_x67UwLVigqTaIkY36RNsrzJPaj6_PW5U6TXAjaJL5V3nfo3w-FK3cChprllriEi6S30N2MwbEZfUCPSTBMLiSWN4TYSRnvD-APrkOs8ipVJvwIP538KI9x4nM4uEAhVvBO8Qv2I-3MkFojW8MhE5QcC0BgGaSJQuJZHKFJ2zziawgYjtWpDTASWQ28fMWveIUtAMfKuk-I2xBmY61wT34L1K8S2dzH0jKc2VQlktrW023bl-bZ_O7s_HKE3keeUHpW3Vn0ta72Unv-prXNKHEwZ2Qz6QKL8lRCrcRZSmluv4d0WXPSaCWUcYopyVLtGEzem6_VNbpwzO-70w

###

POST https://localhost:3103/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=backend-for-frontend&client_secret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0&grant_type=refresh_token&refresh_token=DF467469E398B0AC8AA19047959ACFB6983381F0F56E7C46F2F6C9B831983BA2-1
