FROM simplebudget/identity/dbmigrator:1.1.0 as base 
WORKDIR /app/src/asg.identity.data.migrator
ENTRYPOINT [ "dotnet", "watch", "run", "./bin/Debug/net7.0/asg.identity.data.migrator.dll", "-migrate" ]