FROM mcr.microsoft.com/dotnet/sdk:7.0 AS dev

# Copy Certs
WORKDIR /usr/local/share/ca-certificates
COPY ./simple-budget/certs/ca ./

#update the certificates for the container
RUN update-ca-certificates 

WORKDIR /https
COPY ./simple-budget/certs/https ./

# Copy Packages to /app/packages
WORKDIR /app/packages
COPY ./packages ./

# Add NuGet source: Local
RUN dotnet nuget add source /app/packages -n local

# Copy Main Project and dependencies
WORKDIR /app/src
COPY ./identity/src/asg.identity ./asg.identity
COPY ./identity/src/asg.identity.data ./asg.identity.data

# Build package
WORKDIR /app/src/asg.identity
RUN dotnet build ./asg.identity.csproj

ENTRYPOINT [ "dotnet", "watch", "run", "./bin/Debug/net7.0/asg.identity.dll" ]